triggers:
  - name: int-t1
    type: trigger
    version:
      counter: 2
      
  - name: int-t2runsh
    type: trigger
    version:
      counter: 0
      
  - name: int-t3runcli
    type: trigger
    version:
      counter: 0
      